### ISSUE TITLE
webdav 无法打开

### ISSUE THREAD

**Issue by 666wcy** [FolderMagic/FolderMagic#10]
有账号和密码弹窗
但是提示Method Not Allowed
最新的这个版本

**Comment by FolderMagic** [comment]
什么客户端，方便的话可以通过代理看下是什么请求。
是不是通过nginx翻袋了？

**Comment by FolderMagic** [comment]
反代需要对应的服务器开放相应的方法

**Comment by 666wcy** [comment]
抱歉，我的原因，这个提示是直接在网页端打开显示的，raildrive端通过ip和nginx反代实测都没有问题，AirExplorerPortable也成功了，之前没有成功应该是我nginx的配置问题，抱歉打扰

**Comment by FolderMagic** [comment]
webdav是无法通过浏览器直接打开的。解决了就好
