### ISSUE TITLE
SSL部署之后，畫廊功能不能使用

### ISSUE THREAD

**Issue by archerlitao** [FolderMagic/FolderMagic#11]
透過nginx1.20配置了SSL之后，發現所有的畫廊功能不能用。圖片文件上傳功能正常，下載不行。畫廊功能不能使用。PDF、word都是可以正常預覽，日志里面沒有錯誤。
放棄SSL，直接用HTTP協議就都是正常的。
謝謝指導一下。

**Comment by archerlitao** [comment]
> 透過nginx1.20配置了SSL之后，發現所有的畫廊功能不能用。圖片文件上傳功能正常，下載不行。畫廊功能不能使用。PDF、word都是可以正常預覽，日志里面沒有錯誤。
> 放棄SSL，直接用HTTP協議就都是正常的。
> 謝謝指導一下。

更新一下，使用raidrive配置SSL映射驅動器，上傳JPG PNG圖片文件，顯示沒有權限。將文件改為其它格式上傳正常

**Comment by archerlitao** [comment]
> 透過nginx1.20配置了SSL之后，發現所有的畫廊功能不能用。圖片文件上傳功能正常，下載不行。畫廊功能不能使用。PDF、word都是可以正常預覽，日志里面沒有錯誤。
> 放棄SSL，直接用HTTP協議就都是正常的。
> 謝謝指導一下。

果然是nginx的配置問題，處理完成了！

**Comment by archerlitao** [comment]
> 透過nginx1.20配置了SSL之后，發現所有的畫廊功能不能用。圖片文件上傳功能正常，下載不行。畫廊功能不能使用。PDF、word都是可以正常預覽，日志里面沒有錯誤。
> 放棄SSL，直接用HTTP協議就都是正常的。
> 謝謝指導一下。

Nginx的配置問題，自行處理完成了。
FolderMagic 功能棒棒的。

**Comment by FolderMagic** [comment]
新版本发布了哦，对文件管理的支持应该是目前最强了~
