### ISSUE TITLE
视频播放器

### ISSUE THREAD

**Issue by uadora** [FolderMagic/FolderMagic#12]
在线视频播放器能不能换成dplayer呢，想要倍速播放功能

**Comment by FolderMagic** [comment]
简单试了下，发现是可以做到的。
不过dplayer并不能支持多字幕，他只能支持一个。

**Comment by FolderMagic** [comment]
经过反复的测试，我发现dplayer的字幕功能是自己实现的，并不能支持手机端自带浏览器的字幕功能，表现为全屏后字幕就消失了。

你有别的播放器推荐吗？

**Comment by FolderMagic** [comment]
1.4版本使用DPlayer，请测试、
