### ISSUE TITLE
建议增加上传文件夹功能

### ISSUE THREAD

**Issue by lululus** [FolderMagic/FolderMagic#15]
我可以通过直接拖动文件来上传文件，但我尝试拖入一个文件夹，却没有上传的反应。

我想应该是没有实现上传文件夹的功能？大佬可以实现一下这个啦

**Comment by lululus** [comment]
另外，登入界面的那个背景图能否支持自定义？

**Comment by FolderMagic** [comment]
上传文件夹功能实现过于复杂且非常容易造成意外情况暂不会考虑。
背景图片只能做成单个图片的可以不

**Comment by lululus** [comment]
要整多个图片的那种的话，我想应该也能通过外链api来解决？如果不好做的话，设定单张图片应该也够了

**Comment by FolderMagic** [comment]
图片使用外链没问题，但是目前外链的图床根本没有什么API规范，完全不可能去兼容什么阿猫阿狗的自制图床的。

多张的最大问题是吃内存。图片都要预加载到内存的，因为程序启动后会chroot，外部文件夹没有读取权利。

**Comment by FolderMagic** [comment]
@lululus 1.4.1版本已支持自定义登录背景功能。

**Comment by lululus** [comment]
> @lululus 1.4.1版本已支持自定义登录背景功能。

谢谢大佬了😄
