### ISSUE TITLE
可以支持一下在线mkv格式播放吗？

### ISSUE THREAD

**Issue by faxlok** [FolderMagic/FolderMagic#17]
下了一个mkv格式的视频，能正常打开但是只有声音，画面是漆黑一片。

**Comment by FolderMagic** [comment]
> 视频预览
> 支持预览mp4, mkv格式，能否成功播放取决于实际视频容器内的编码格式。

mkv和mp4均属于容器格式，内部的编码是不确定的，是否支持完全由实际内部的编码决定。浏览器支持的格式非常有限，所以只有部分mkv和mp4才能在浏览器中播放。

**Comment by faxlok** [comment]
> > 视频预览
> > 支持预览mp4, mkv格式，能否成功播放取决于实际视频容器内的编码格式。
> 
> mkv和mp4均属于容器格式，内部的编码是不确定的，是否支持完全由实际内部的编码决定。浏览器支持的格式非常有限，所以只有部分mkv和mp4才能在浏览器中播放。

噢，我知道了，谢谢解答
