### ISSUE TITLE
功能需求建议：下载文件夹

### ISSUE THREAD

**Issue by IMZCC** [FolderMagic/FolderMagic#18]
希望可以支持打包文件夹然后下载

**Comment by FolderMagic** [comment]
这个功能其实一点也不难实现，之所以不做是因为这个功能没价值。

实时zip是不压缩的，意味着你下载的数据一点也不会变小。实时压缩不支持断点续传也不支持多线程，意味着下载超级慢并且中断后无法继续下载…

**Comment by FolderMagic** [comment]
你可以使用webdav，非常适合下载数量庞大的小文件。

未来考虑下如果内存占用没问题的话也可以加上，很好实现。

**Comment by liouxunhuan8** [comment]
对于我这样的经常要从PT上下载文件的人来说 
这个功能还是特别需要的

**Comment by FolderMagic** [comment]
已支持zip下载文件夹的功能。

**Comment by liouxunhuan8** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
