### ISSUE TITLE
手机Chrome浏览器下载APK文件后缀会变为.zip

### ISSUE THREAD

**Issue by NicolasKun** [FolderMagic/FolderMagic#2]
手机型号: Mi 9、Samsung S10
Chrome: 81、 85
解决方案: mime type增加 application/vnd.android.package-archive

希望大佬解决这个问题🥳

![](https://ftp.bmp.ovh/imgs/2020/09/2d90a2d4aec83e85.jpeg)

**Comment by FolderMagic** [comment]
我自己没用安卓，不知道有这个问题。很快会修改好

**Comment by FolderMagic** [comment]
已解决。
