### ISSUE TITLE
共享管理的JS出现404导致显示空白

### ISSUE THREAD

**Issue by Nisekoi5** [FolderMagic/FolderMagic#20]
版本是最新版，现点击分享列表为空白。F12查看发现是shareman这个js 404了。未使用nginx等软件反向代理。直接访问的监听端口
程序目录在/www/下，启动命令为。
./FolderMagic --root=/data/userfiles --bind=:33333  --auth=admin:w*******a --nosearch --bg=poste
![log](https://user-images.githubusercontent.com/49276902/136897082-94ed5010-da3f-438e-b2ad-b2729b1e0f10.jpg)
r

**Comment by FolderMagic** [comment]
ctrl+F5忽略缓存刷新，或者在开发者工具中忽略缓存刷新就可以了。
每次新版本js和css的名称都会变的。

**Comment by Nisekoi5** [comment]
> ctrl+F5忽略缓存刷新，或者在开发者工具中忽略缓存刷新就可以了。 每次新版本js和css的名称都会变的。

是这个原因。强制刷新一下ok了。谢谢
