### ISSUE TITLE
linux  修改日期 字段 时间显示不对

### ISSUE THREAD

**Issue by stevenrao** [FolderMagic/FolderMagic#25]
修改日期 相差8个小时。

**Comment by FolderMagic** [comment]
测试没有任何问题。
修改日期按服务器时间展示，请你检查linux服务器上的时区。

**Comment by stevenrao** [comment]
timedatectl
      Local time: Wed 2021-12-22 12:18:51 CST
  Universal time: Wed 2021-12-22 04:18:51 UTC
        RTC time: Wed 2021-12-22 04:18:50
       Time zone: Asia/Shanghai (CST, +0800)
 Network time on: no
NTP synchronized: yes
 RTC in local TZ: no

**Comment by stevenrao** [comment]
![image](https://user-images.githubusercontent.com/6369621/147035007-8558e947-1ab3-48e3-a391-7664b1c35270.png)
明明是上午上传的，显示凌晨。
linux 文件系统显示时间
![image](https://user-images.githubusercontent.com/6369621/147035137-b5cf75e6-7c19-4ccf-9b3b-9cf016438298.png)

**Comment by FolderMagic** [comment]
我看了下代码，似乎确实没有做时区，应该确实存在问题。

**Comment by FolderMagic** [comment]
[FolderMagic-hotfix.zip](https://github.com/FolderMagic/FolderMagic/files/7760338/FolderMagic-hotfix.zip)
你好，请使用附件中的文件测试一下是否时间已经恢复正常。
