### ISSUE TITLE
linux上播放视频失败，而且会导致服务处于假死状态，需要重启解决

### ISSUE THREAD

**Issue by stevenrao** [FolderMagic/FolderMagic#26]
linux上播放视频失败，而且会导致服务处于假死状态，此时无论如何刷新浏览器，都看不到内容。 浏览器处于等待应答状态，刷新按钮一直处于X状态

需要重启服务恢复才行

**Comment by FolderMagic** [comment]
你说的linux上播放视频是指客户端是linux还是服务端是linux？

**Comment by stevenrao** [comment]
服务端是在linux  ubuntu 18.04。
浏览器使用chrome  版本 96.0.4664.110（正式版本） （64 位），window 11 上

**Comment by FolderMagic** [comment]
有个原理需要清楚，对于服务端来说，播放视频=下载文件，播放这件事情是由客户端的浏览器完成的，对服务端来说不存在播放视频这件事情。
所以问题其实在于你的网络卡住了。建议你关闭服务端的http2支持，只使用普通https

**Comment by FolderMagic** [comment]
http2存在多路复用，这个特性会导致一个连接卡住，所有连接就全部卡住，但https不会这样，http也不会。如果你的网络比较不稳定，http2容易造成你遇到的问题。但是无法播放视频时，那个下载视频的连接并没有正常结束，和服务端继续保持着通信，从而导致其他连接也完全发不出去。你换别的软件也无法改变这个结果。

**Comment by stevenrao** [comment]
> 有个原理需要清楚，对于服务端来说，播放视频=下载文件，播放这件事情是由客户端的浏览器完成的，对服务端来说不存在播放视频这件事情。 所以问题其实在于你的网络卡住了。建议你关闭服务端的http2支持，只使用普通https

但是关闭浏览器解决不了问题，需要重试linux上服务才能解决问题。

**Comment by FolderMagic** [comment]
如果你在使用http2，建议关闭这个功能。同时你可以在电脑无法访问时试试通过手机访问。

FolderMagic使用的就是普通的go http server，所以对于连接问题没有多少我可以做的。

**Comment by stevenrao** [comment]
业务场景是这样： 分享某个存储给其他人使用，结果其中一个人操作，导致其他所有人都无法使用恢复。要等待后台服务维护人去重启才能继续浏览其他普通文件。 如果能通过关闭浏览器tab解决或许体验好很多。

目前只在视频文件地方遇到这种问题。但是没有办法禁止别人点击视频文件播放操作，如果能加个启动参数，关闭播放视频功能，或许能缓解这种问题。

**Comment by FolderMagic** [comment]
你可以试试这样操作：
让那个无法播放的人右键点击另存为，同时其他人继续访问。

播放视频和下载对于服务端来说和正常下载的区别就是播放视频会发起多个连接，有时还会从中间开始下载。其他和下载没有区别。
