### ISSUE TITLE
webdav只能显示系统根目录的磁盘空间

### ISSUE THREAD

**Issue by DarkerWhite** [FolderMagic/FolderMagic#27]
新版本能够显示磁盘空间了，但是似乎只能显示系统根目录（/）的空间情况。

我有一台服务器，在某个位置（/root/drive）设置了一个挂载点，挂载了一个硬盘。

我在启动FolderMagic的时候用-r指定了FolderMagic的根目录为（/root/drive），但这样显示出来的磁盘信息还是系统根目录（/）的。

是否能让FolderMagic能以-r指定的目录为标准来显示磁盘信息？

**Comment by FolderMagic** [comment]
我还没有测试过这种情况，有空了我试下

**Comment by FolderMagic** [comment]
1.4.3 版本已解决此问题。
