### ISSUE TITLE
大佬，这个可以搞一个windows版本的出来吗

### ISSUE THREAD

**Issue by langren1353** [FolderMagic/FolderMagic#3]

**Comment by FolderMagic** [comment]
可以编译出Windows版本，但是搜索不能使用，因为Windows的搜索机制和Linux有所不同。
另外Windows下文件系统和Linux有所不同，没有严格测试过，所以肯定会出现比较多的问题。另外也没有多少人需要Windows列表。

**Comment by langren1353** [comment]
足够了足够了，不需要搜索功能也挺好的，本来预期就是想拿来预览整个文件夹，没找到合适的东西，其他的都要安装环境，比较麻烦了。大佬可以编译一个出来吗，mark一下搜索功能不能用就行了的

**Comment by FolderMagic** [comment]
已添加。
