### ISSUE TITLE
使用后的一点建议(😂

### ISSUE THREAD

**Issue by KyAaron** [FolderMagic/FolderMagic#4]
首先感谢大佬开发的程序!
我体验一段时间后!希望能够加一个访客登录(启动时设置的user就是管理员)能够给访客设定访问目录!
另外希望能发布一个arm32位(armv7)的版本

**Comment by FolderMagic** [comment]
暂时不会考虑多用户的情况。另外程序目前是使用chroot保护的，在这种状态下，除了设定目录外的任何目录都无法被访问到的，即便允许设置访客目录也只能是管理员目录中的一个子目录，不可以是独立的外部目录。

**Comment by KyAaron** [comment]
> 暂时不会考虑多用户的情况。另外程序目前是使用chroot保护的，在这种状态下，除了设定目录外的任何目录都无法被访问到的，即便允许设置访客目录也只能是管理员目录中的一个子目录，不可以是独立的外部目录。

大佬，我想要的访客登录就是在管理员下的子目录额，另外关系分享设置，能否对单个文件进行分享链接的获取呢!(或者在分享链接管理里面能对单个记录进行复制)，分享的文件，其他陌生人访问都得登录!这个有办法改改吗，分享文件能不登陆直接下载这样的

**Comment by FolderMagic** [comment]
右键菜单复制的链接就是不需要登录的，应该是token=xxxx的形式。

**Comment by KyAaron** [comment]
> 右键菜单复制的链接就是不需要登录的，应该是token=xxxx的形式。

好的，谢谢啦!永久链接的确不用登录!还是希望能有个更方便的形式来进行分享(不论永久链接还是临时链接都是一次性复制目录下全部文件的链接😂)

**Comment by FolderMagic** [comment]
你要对着单个文件点右键，获得的就是那个文件的链接，空白处点就是全部。
临时链接在限定时间内也是不用登陆的

**Comment by FolderMagic** [comment]
右键菜单会根据点击的内容不同而不同，全部链接会有 复制所有xx链接字样，单个链接就是简单的 复制xx链接。

临时链接是auth=xxx，永久是token=xxx

**Comment by KyAaron** [comment]
> 你要对着单个文件点右键，获得的就是那个文件的链接，空白处点就是全部。
> 临时链接在限定时间内也是不用登陆的

大佬，我又试了下，在pc端的浏览器的确和你说的交互方式一样!但是到手机浏览器就不好使了，安卓手机，好几个浏览器都试了(开桌面模式)，右键依然不行!

**Comment by FolderMagic** [comment]
右键交互没有对手机优化过，只考虑了桌面。
这个会在之后改进。

**Comment by KyAaron** [comment]
> 右键交互没有对手机优化过，只考虑了桌面。
> 这个会在之后改进。

大佬，能否麻烦发布一armv7(arm32位)的版本，想在32位的设备上运行!!!

**Comment by FolderMagic** [comment]
32位arm7已添加。没有功能性改进，不支持webp。

**Comment by KyAaron** [comment]
> 32位arm7已添加。没有功能性改进，不支持webp。
大佬，我刚到家在armv7的设备上试了下，不能运行呀!
![Uploading IMG_20201020_211522.jpg…]()

**Comment by FolderMagic** [comment]
> > 32位arm7已添加。没有功能性改进，不支持webp。
> > 大佬，我刚到家在armv7的设备上试了下，不能运行呀!
> 
> ![IMG_20201020_211522](https://usercontent.githubfast.com/camo/2b7c3e341a8c961c8059d13ace456b7a5b911677/68747470733a2f2f6b79616172696e2e636f64696e672e6e65742f702f786274632f642f786274632f6769742f7261772f6d61737465722f696d616765732f494d475f32303230313032305f3231313532322e6a7067)

传错了。。。。已经重新上传了

**Comment by KyAaron** [comment]
> > > 32位arm7已添加。没有功能性改进，不支持webp。
> > > 大佬，我刚到家在armv7的设备上试了下，不能运行呀!
> > 
> > 
> > ![IMG_20201020_211522](https://camo.githubusercontent.com/85ac10411915d7bf46e2bd7f17c0b5e3d4214efd/68747470733a2f2f75736572636f6e74656e742e676974687562666173742e636f6d2f63616d6f2f326237633365333431613863393631633830353964313361636534353662376135623931313637372f36383734373437303733336132663266366237393631363137323639366532653633366636343639366536373265366536353734326637303266373836323734363332663634326637383632373436333266363736393734326637323631373732663664363137333734363537323266363936643631363736353733326634393464343735663332333033323330333133303332333035663332333133313335333233323265366137303637)
> 
> 传错了。。。。已经重新上传了

ok啦，大佬的辛苦了!!!

**Comment by FolderMagic** [comment]
> > 你要对着单个文件点右键，获得的就是那个文件的链接，空白处点就是全部。
> > 临时链接在限定时间内也是不用登陆的
> 
> 大佬，我又试了下，在pc端的浏览器的确和你说的交互方式一样!但是到手机浏览器就不好使了，安卓手机，好几个浏览器都试了(开桌面模式)，右键依然不行!

我试了安卓Chrome，长按条目可以正确的弹出右键菜单，没有出现你说的问题。不需要桌面模式。
