### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by PRStarDust** [FolderMagic/FolderMagic#5]
首先感谢大佬的工作，我将它搭建在N1上，可以方便地通过网页管理我的硬盘了。用了几天感觉很好，不知道以后能否加入以下功能呢？

- 上传文件按钮。现在只能通过拖拽文件到网页上完成上传的操作感觉还是不太方便，而且手机也没办法实现文件上传，如果能够添加一个上传文件的按钮想必更加方便。

- 文件管理功能增强。现在文件与目录可以新建删除下载，就差重命名、移动和复制了。

**Comment by FolderMagic** [comment]
针对手机的优化会添加的，会想办法让手机也有基础的操作能力。

文件管理增强暂不考虑。重命名，移动和复制会大大增加前后端的复杂度，比如重名情况，记录当前复制的状态等等

**Comment by PRStarDust** [comment]
好的，谢谢大佬👌🤣

**Comment by FolderMagic** [comment]
1.1版本实现了对移动端的适配。
