### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by tongenlian** [FolderMagic/FolderMagic#6]
首先感谢大佬开发的这个程序，挺有用的，另外就是音乐这块儿能不能添加下flac格式呢；图片预览的时候是否可以增加下左右切换上下一张的箭头呢？
谢谢

**Comment by FolderMagic** [comment]
Flac 浏览器是不支持的，只能通过后台动态转码，但就不是无损了。

图片可以改。

**Comment by FolderMagic** [comment]
查了下发现Chrome已经支持flac了，我试试能不能实现。

**Comment by tongenlian** [comment]
好的，多谢大佬

**Comment by tongenlian** [comment]
大佬，还有个小建议哈，就是平常使用的时候有个用法就是html文件能不能给多加个选择就是直接在浏览器中渲染打开，因为现在是显示的源码，想着看看能不能在线浏览页面那种的😊

**Comment by FolderMagic** [comment]
经过测试可以完美支持flac格式。
html的只能在新页面打开，浮窗支持html是做不到的，因为会存在css污染的问题。

**Comment by FolderMagic** [comment]
> 大佬，还有个小建议哈，就是平常使用的时候有个用法就是html文件能不能给多加个选择就是直接在浏览器中渲染打开，因为现在是显示的源码，想着看看能不能在线浏览页面那种的😊

文本类的打开默认是预览源代码，鼠标放到预览上会在右下角展示一个 下载 按钮，点击就会直接使用浏览器预览了。

**Comment by tongenlian** [comment]
> 经过测试可以完美支持flac格式。
> html的只能在新页面打开，浮窗支持html是做不到的，因为会存在css污染的问题。可以iframe，但毕竟存在安全性问题。

是的，就是新页面打开的那种的，因为有的时候会上传离线html页面进行浏览这种的

**Comment by tongenlian** [comment]
麻烦问下哈，是否可以提供右键修改文件名的功能呢，挺实用的

**Comment by FolderMagic** [comment]
更强大的文件管理功能将在未来逐步实现。

图片预览等功能将在近期更新。

**Comment by FolderMagic** [comment]
图片画廊及flac、html支持已发布。

**Comment by tongenlian** [comment]
> 图片画廊及flac、html支持已发布。

666

**Comment by FolderMagic** [comment]
1.3版本已实现对文件重命名和移动的完整支持。

**Comment by FolderMagic** [comment]
1.3版本已实现对文件重命名和移动的完整支持。
