### ISSUE TITLE
无法在RaspBerry Pi OS 上正常运行

### ISSUE THREAD

**Issue by MoeMion** [FolderMagic/FolderMagic#7]
release FolderMagic_arm7无法在Raspberry Pi OS（# cat /etc/issue Raspbian GNU/Linux 10）上正常运行。
问题描述：
root@raspberrypi:/home# ./foldermagic 
Sharing / on :80 ...
root@raspberrypi:/home#

**Comment by FolderMagic** [comment]
80端口是不是被占用了

**Comment by MoeMion** [comment]
有尝试使用-bind 参数来更换端口，以下是log:
root@raspberrypi:/home# ./foldermagic -bind 2345
Sharing / on 2345 ...
root@raspberrypi:/home#

**Comment by FolderMagic** [comment]
试试nosearch参数关闭搜索

**Comment by FolderMagic** [comment]
bind需要用:1234

**Comment by MoeMion** [comment]
bind参数添加:后正常运行 感谢
