### ISSUE TITLE
闪退无法启动？

### ISSUE THREAD

**Issue by BlueSkyXN** [FolderMagic/FolderMagic#8]
![image.png](https://img01.sogoucdn.com/app/a/100540022/2021032710444670220244.png)
![image.png](https://img03.sogoucdn.com/app/a/100540022/2021032710443362284786.png)

权限已经拉满，直接上传和解压都试过，换了2台机器也试过，表现都是开启监听端口后就闪退，不会进入扫描路径

**Comment by FolderMagic** [comment]
同 #7 bind后面跟的是地址 ip:port，或者:port，不是直接写端口

**Comment by BlueSkyXN** [comment]
> 同 #7 bind后面跟的是地址 ip:port，或者:port，不是直接写端口，请注意有冒号
> 
> 根据go的规范 :port = 0.0.0.0:port，若不想监听所有接口，则需要指定ip

哈哈哈，我刚刚也发现了，拿了没开nginx试了一下，需要加:
